### ISSUE TITLE
Add sentry setup for development

### ISSUE THREAD

**Issue by tuxdna** [fabric8-analytics/fabric8-analytics-deployment#21]
We do not have any setup to verify that Sentry is capturing correct errors at the moment such as : 

 * https://github.com/openshiftio/openshift.io/issues/2535

This setup will help us ensure that we capture such errors.

**Comment by msrb** [comment]
I am not sure if we need Sentry for local deployment - I'd say not. Note the referenced issue is from prod.

**Comment by tuxdna** [comment]
We need some way to verify that our exceptions also reach Sentry. We may not want to add it to the local setup but somehow ensure that when we log exceptions, they also reach Sentry.

**Comment by tuxdna** [comment]
Another idea is to setup an account for onself here and use that DSN instead: https://sentry.io/signup/?referrer=docs

Suggestions welcome.

**Comment by geetikabatra** [comment]
I agree with @tuxdna. We need something for local deployment. It will be really hard to debug the issue without setup in local.

**Comment by msrb** [comment]
Definitely +1 on documentation how to debug Sentry locally, but let's not enable it by default for everybody.

**Comment by msrb** [comment]
I believe @pkajaba was testing the integration locally when he was adding support to workers.
Pavel, could you please weigh in here?

**Comment by pkajaba** [comment]
I am not sure what this issue is about. Support for remote sentry configuration was already introduced in https://github.com/fabric8-analytics/fabric8-analytics-deployment/pull/13. All you have to do now, is to define Sentry DSN in docker-compose and you are good to go.

Are we talking about deploying our own instance for local development? I would be strongly against such move since my laptop is already running low on resources when I am trying to deploy locally. 

@tuxdna @msrb

**Comment by tuxdna** [comment]
These steps work for me:

 * I created an account sentry.io as mentioned in my earlier comment. 
* I created a Python ( Flask ) project in sentry.io under my account.
* Then I was presented with SENTRY DSN to be used.
* I added the above SENTRY DSN to docker compose file.

By following above steps I was able to send exceptions messages to sentry.io in my project and verify if our changes are working fine.

With this we can close this issue.

@msrb @GeetikaBatra @pkajaba

**Comment by pkajaba** [comment]
why don't you use RH's Sentry deployment? You can create your sentry project there.

**Comment by tuxdna** [comment]
@pkajaba Use whatever works for you since it is only for local setup.

**Comment by pkajaba** [comment]
> @pkajaba Use whatever works for you since it is only for local setup.

it's true, but it might pose the problem if sentry prints some credentials. It's always better to have it just on RH's instance vs. sentry public one.

**Comment by geetikabatra** [comment]
@tuxdna 👍 , I am following the same steps, but  instead of creating an account on sentry.io, I created a project under RH sentry deploymnet as suggested by @pkajaba, 
https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-worker_test/
